name: "Pipeline de Seguridad Java"

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  # LLAMADA ÚNICA AL ORQUESTADOR
  gobernanza-global:
    uses: DevSecOps-Uni-Project/.github/.github/workflows/main-security.yml@main
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}