name: Trigger auto deployment for ids-backend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ feature/gemini-ai-integration ]
    paths:
    - '**'
    - '.github/workflows/ids-backend-AutoDeployTrigger-322ef61e-e698-4a1c-9d21-a1251faee987.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.IDSBACKEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.IDSBACKEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.IDSBACKEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          dockerfilePath: Dockerfile
          registryUrl: idsbackendregistry-auhkc9bfcrbghfe8.azurecr.io
          registryUsername: ${{ secrets.IDSBACKEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.IDSBACKEND_REGISTRY_PASSWORD }}
          containerAppName: ids-backend
          resourceGroup: arsw
          imageToBuild: idsbackendregistry-auhkc9bfcrbghfe8.azurecr.io/ids-backend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


