name: "Ejecución de Auditoría de Seguridad"

on:
  push:
    branches: 
      - main
      - 'feat/**'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  call-governance:
    permissions:
      contents: read
      packages: write
      security-events: write
      actions: read
      pull-requests: write

    uses: DevSecOps-Uni-Project/.github/.github/workflows/main-security-pipeline.yml@main
    with:
      java-version: '21'
    secrets:
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      DEPENDABOT_PAT: ${{ secrets.DEPENDABOT_PAT }}